### ISSUE TITLE
[API Docs Conflict] CollectionMetaResponseFile.id

### ISSUE THREAD

**Issue by jacobhumston-school** [Lovely-Experiences/sxcu.api#1]
CollectionMetaResponseFile.id is undefined despite the docs stating that the value is a snowflake. This issue is a reminder to resolve this conflict.

**Comment by jacobhumston** [comment]
Solved!
<img width="354" alt="Code_104az0Lett" src="https://user-images.githubusercontent.com/57332486/214210402-82cc5cab-c9a4-4d49-a37c-4d0092b0ccff.png">
